### ISSUE TITLE
Checklist for submitting formal review

### ISSUE THREAD

**Issue by kuziekj** [kylemath/mne-python#24]
Here is a checklist of things to complete before submitting a formal review. An abridged version from info on this site:

https://mne.tools/stable/install/contributing.html#mne-python-coding-conventions

- [ ] Test coverage for new functionality (test output of boxy.py and compare to another source, such as p_pod)

- [ ] Document new functionality (thorough docstring explanations and tutorials explaining functionality)

- [x] Avoid public API changes if possible (don't think we've made any such changes... Just added our own functions)

- [x] Add deprecation warnings if removing/changing functionality (again, don't think this applies to us)

- [ ] Describes changes in the changelog, "doc/whats_new.rst" (sounds like this should be done AFTER the PR is finalised)

- [ ] Test locally before opening PR (kind of did both, tested locally and using CI tests)

- [ ] Make tests fast and thorough (currently tests compare raw, epoch, evoke to p_pod. Anything else? Need to make smaller data files for such tests)

- [x] adhere to pep8 (currently seems fine, but can check by running "make flake")

- [ ] Use consistent variable names (should make sure variable names make sense too)

- [x] follow NumPy style for docstrings (again, should be fine now but can be checked by running "make docstyle")

- [x] Docstrings and documentation pages should cross-reference mentioned classes, functions, etc. (can probably use the "plot_70" tutorial as an example)

- [x] Use single quotes where possible

- [x] Prefer generators or comprehensives over filter() and map() (need to check into this...)

- [x] Use explicit functional constructors (eg. list(), dict(), set())

- [x] Avoid nested functions or class methods if possible

- [x] Avoid *args and **kwargs in function/method signatures

- [x] Import in this order (python built-in > standard scientific (eg. numpy, scipy) > others > MNE imports)

- [x] Methods should modify in-place and return self

- [x] Functions should return copies, where applicable

- [x] Docstrings should contain informative names for return values, even if that particular name isn't used

- [x] Visualisation capabilities should be available in method and function form

**Comment by kylemath** [comment]
thanks for getting this together, glad we have already done most, I think we are almost there

**Comment by kuziekj** [comment]
Yeah I think we're getting close. Helps that a lot of the checklist doesn't really apply to us since we're basing the code on what's already in mne.

**Comment by kuziekj** [comment]
I made a PR to address the list: https://github.com/kylemath/mne-python/pull/25
